### PR TITLE
[WIP] Canonical functions support

### PR DESCRIPTION
**Pull request by Thorium**
*Canonical functions are SQL-specific functions to each database. We translate .NET-functions to native database functions.*

Done some refactoring for easier implementation. 

How to implement a new function:
1. Add function to SqlRuntime.Patterns (near comment `// These are canonical functions`)
2. Add provider spesific implementations for each providers `fieldNotation`-function
3. Add unit tests :-)

Currently support for:
- For strings: 
   - [x] Substring, 
   - [x] Concat,
   - [x] toUpper, toLower
   - [x] Trim
- For numerics: 
   - [x] Abs, 
   - [x] Basic arithmetics (add,substract,multiply,divide)
   - [x] Somekind of rounding for decimals 
- For dates (needs more testing): 
   - [x] Day,Month,Year, 
   - [x] And adding them. 
   - [x] Removing time-component
- Others:
   - [ ] case-clause

Hmm... Interesting that SQLite Substring starts from 1 and .NET from 0. Should we try to convert those also to .NET-style?

Ping #390

### CODE REVIEW

**Comment by Thorium** [comment]
More testing needed, everything is not perfect yet (at least date-functions, and alias-resolving on deep hierarchies seems to have some minor bugs still). These are what I used (looked from the manuals, I don't have all the databases installed):

#### .NET String Functions (.NET)

| .NET          | MsSqlServer     | PostgreSql   | MySql      | Oracle      | SQLite | MSAccess| Odbc        |  Notes
|---------------|-----------------|--------------|------------|-------------|--------|---------|-------------|--------------------------|
.Substring(x)   | SUBSTRING       | SUBSTRING    | MID        | SUBSTR      | SUBSTR | Mid     | SUBSTRING   | Start position may vary. |
.Substring(x, y)| SUBSTRING       | SUBSTRING    | MID        | SUBSTR      | SUBSTR | MID     | SUBSTRING   | (0 or 1 based.) |
.ToUpper()      | UPPER           | UPPER        | UPPER      | UPPER       | UPPER  | UCase   | UCASE       |                 |
.ToLower()      | LOWER           | LOWER        | LOWER      | LOWER       | LOWER  | LCase   | LCASE       |                 |
.Trim()         | LTRIM(RTRIM)    | TRIM(BOTH...)| TRIM       | LTRIM(RTRIM)| TRIM   | Trim    | LTRIM(RTRIM)|                 |
.Length()       | DATALENGTH      | CHAR_LENGTH  | CHAR_LENGTH| LENGTH      | LENGTH | Len     | CHARACTER_LENGTH |            |
.Replace(a, b)  | REPLACE         | REPLACE      | REPLACE    | REPLACE     | REPLACE| Replace | REPLACE     |                 |
.IndexOf(x)     | CHARINDEX       | STRPOS       | LOCATE     | INSTR       | INSTR  | InStr   | LOCATE      |                 |
.IndexOf(x, i)  | CHARINDEX       |              | LOCATE     | INSTR       |        | InStr   | LOCATE      |                 |
(+)             | `+`             | `||`         | CONCAT     | `||`        | `||`   | &       | CONCAT      |                 |

In where-clauses you can also use `.Contains()`, `.StartsWith()` and `.EndsWith()`, which are translated to 
corresponding `LIKE`-clauses (e.g. StartsWith("abc") is `LIKE ('asdf%')`

#### .NET DateTime Functions

| .NET         | MsSqlServer    | PostgreSql| MySql    | Oracle    | SQLite  | MSAccess  | Odbc      |  Notes
|--------------|----------------|-----------|----------|-----------|---------|-----------|-----------|--------------------------|
.Date          | CAST(AS DATE)  | DATE_TRUNC| DATE     | TRUNC     | STRFTIME| DateValue(Format)| CONVERT(SQL_DATE)  |   |
.Year          | YEAR           | DATE_PART | YEAR     | EXTRACT   | STRFTIME| Year      | YEAR       |   |
.Month         | MONTH          | DATE_PART | MONTH    | EXTRACT   | STRFTIME| Month     | MONTH      |   |
.Day           | DAY            | DATE_PART | DAY      | EXTRACT   | STRFTIME| Day       | DAYOFMONTH |   |
.Hour          | DATEPART HOUR  | DATE_PART | HOUR     | EXTRACT   | STRFTIME| Hour      | HOUR       |   |
.Minute        | DATEPART MINUTE| DATE_PART | MINUTE   | EXTRACT   | STRFTIME| Minute    | MINUTE     |   |
.Second        | DATEPART SECOND| DATE_PART | SECOND   | EXTRACT   | STRFTIME| Second    | SECOND     |   |
.AddYears(i)   | DATEADD YEAR   | + INTERVAL| DATE_ADD | + INTERVAL| DATE    | DateAdd   |            |   |
.AddMonths(i)  | DATEADD MONTH  | + INTERVAL| DATE_ADD | + INTERVAL| DATE    | DateAdd   |            |   |
.AddDays(f)    | DATEADD DAY    | + INTERVAL| DATE_ADD | + INTERVAL| DATE    | DateAdd   |            | .NET has float, bus SQL may ignore decimal fraction |
.AddHours(f)   | DATEADD HOUR   | + INTERVAL| DATE_ADD | + INTERVAL| DATE    | DateAdd   |            |   |
.AddMinutes(f) | DATEADD MINUTE | + INTERVAL| DATE_ADD | + INTERVAL| DATE    | DateAdd   |            |   |
.AddSeconds(f) | DATEADD SECOND | + INTERVAL| DATE_ADD | + INTERVAL| DATE    | DateAdd   |            |   |

#### Numerical Functions (e.g. Microsoft.FSharp.Core.Operators)

| .NET          | MsSqlServer| PostgreSql| MySql   | Oracle| SQLite     | MSAccess| Odbc    |  Notes
|---------------|------------|-----------|---------|-------|------------|---------|---------|--------------------------|
abs(i)          | ABS        | ABS       | ABS     | ABS   | ABS        | Abs     | ABS     |   |
ceil(i)         | CEILING    | CEILING   | CEILING | CEIL  | CAST + 0.5 | Fix+1   | CEILING |   |
floor(i)        | FLOOR      | FLOOR     | FLOOR   | FLOOR | CAST AS INT| Int     | FLOOR   |   |
round(i)        | ROUND      | ROUND     | ROUND   | ROUND | ROUND      | Round   | ROUND   |   |
Math.Round(i,x) | ROUND      | ROUND     | ROUND   | ROUND | ROUND      | Round   | ROUND   |   |
truncate(i)     | TRUNCATE   | TRUNC     | TRUNCATE| TRUNC |            | Fix     | TRUNCATE|   |
(+)             | +          | +         | +       | +     | +          | +       | +       |   |
(-)             | -          | -         | -       | -     | -          | -       | -       |   |
(*)             | *          | *         | *       | *     | *          | *       | *       |   |
(/)             | /          | /         | /       | /     | /          | /       | /       |   |
(%)             | %          | %         | %       | %     | %          | %       | %       |   |

#### Aggregate Functions 

Also you can use these on group-by clause:
`COUNT`, `SUM`, `MIN`, `MAX`, `AVG`

**Comment by Thorium** [comment]
Ping also #388

**Comment by pezipink** [comment]
fantastic work!

**Comment by Thorium** [comment]
@pezipink just to confirm: current `type alias = string` refers always to a table-alias, never a column-alias. So it could be bind pretty tightly to column's key-name, as operators like `StartsWith` or `Concat` never need a table-alias themselves (only their leaf nodes). And instead of a string maybe it could be something to keep type-level track of the process like:

```fsharp
type TableAlias =
| Unresolved of string
| Resolved of string
```

**Comment by Thorium** [comment]
Ok, I think this is ready for merge.

**Comment by dsyme** [comment]
Wow, fantastic work!

**Pull request merged**
