### PR TITLE
fix wrong typemapping for timestamp types in #188

### PR DESCRIPTION
**Pull request by coolya**
Fixes problems with npgsql 3.o which caused columns to disappear.

### CODE REVIEW

**Comment by coolya** [comment]
Seems like it does not fix the problem fully. Looks like timestamps now only include the date not the time.

**Comment by coolya** [comment]
Even without my change and the old npgsql 2.2.7 i have the same issue that `timestamp` field only contain the date part and no time.

**Comment by coolya** [comment]
After doing the changes from #219 it worked fine with npgsql 3.0

**Comment by colinbull** [comment]
Sorry, for the delay. Does this retain compatibility with 2.2.7, was it simply an incorrect type mapping?

**Comment by colinbull** [comment]
Thanks.

**Comment by coolya** [comment]
I tried it with 2.2.7 and it seems to work fine. Not sure if it was in general wrong. I wasn't able to find the docs for npgsql. There it seems to have worked with the old mapping but these classes where removed in 3.0.

**Pull request merged**
