### PR TITLE
overload for SubmitUpdates

### PR DESCRIPTION
**Pull request by Thorium**
Possible solution for #310

### CODE REVIEW

**Comment by isaacabraham** [comment]
Confused - I was talking about the Update() method on the provided data table?

**Comment by pezipink** [comment]
We only use DataTables internally,  are you looking at the right project? :)

**Comment by pezipink** [comment]
In other news, I like the idea of doing something about this but I think it warrants further discussion.  

Allowing failed inserts in a batch invalidates the idea of a transaction completely so I would consider having this as something separate from our standard ORM style processing model.  Currently we always use transactions, don't we?  So what exactly is this change doing?  If one entity fails, the whole lot gets rolled back and the entity statuses are unchanged, right?   That is what it used to do as far as I recall?

**Comment by isaacabraham** [comment]
Doh. This is for the wrong repo. Sorry.

**Comment by isaacabraham** [comment]
At least someone else found this to be a good idea though!

**Comment by Thorium** [comment]
hehe

**Comment by Thorium** [comment]
If the whole transaction fails, then

- The default behaviour should be as is (e.g. for compatibility reasons).
- User could decide what to do with the failed objects: If they are left to the context then probably every future update will also fail. So probably we just want to cancel the whole transaction and clear all the objects and pretend that nothing has happened. Not always, but as I would think this is quite general functionality (e.g. with a webserver where one user managing to feed invalid objects shouldn't mess all others) we could at least give users easy option to do this.
- It would be also nice if the error message would tell the failed objects

**Comment by Thorium** [comment]
We don't need more source code just for fun so if there is not actual need for this I close it now without merging.

**Pull request closed without merging**
