### PR TITLE
Context schema cache support

### PR DESCRIPTION
**Pull request by object**
I ran more tests (applied your PR), and it worked great. I was able to generate a schema cache for the whole solution, then disconnect from the database and use the cache in compilation. The issue I had with incomplete cache was no longer reproducible.

### CODE REVIEW

**Comment by Thorium** [comment]
Great! Now we would need documentation, but the documentation generation is also broken at least in my machine.

**Comment by object** [comment]
Documentation generation is also broken on my machine for the moment. I can write a doc if you point me to right file/section where is should be written.

**Comment by Thorium** [comment]
It could be its own page, but this should also do:
https://github.com/fsprojects/SQLProvider/blob/master/docs/content/core/parameters.fsx

**Comment by object** [comment]
Sent a PR with updated docs.

**Pull request merged**
