### PR TITLE
Ssdt tests

### PR DESCRIPTION
**Pull request by JordanMarr**
## Proposed Changes
* Added a new SSDT test project
* Fixed a few bugs in the view parser
* Fixed bullets in the SSDT documentation

## Types of changes

What types of changes does your code introduce to SQLProvider?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Build and tests pass locally
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Further comments

I intended to implement stored procedures today, but it turned out to be more complex than a last-minute add.
After looking at what will need to be done, I think that both the views and stored procedures will ultimately require some sort of a visitor pattern in order to untangle nested queries.  Once that is in place, then it will just be a matter of implementing enough of the common stuff to make it good enough.  

So after that I decided that my time today would be better spent creating a test project since it will definitely be necessary moving forward.

### CODE REVIEW

**Comment by JordanMarr** [comment]
The announcement [blog post](https://jordanmarr.github.io/fsharp/ssdt-type-provider/) is queued up and ready to post once this goes live. 😀

**Comment by Thorium** [comment]
Thanks! Merged and released to NuGet 1.1.96.

**Comment by Thorium** [comment]
SQLProvider Stored procedures return values are not strongly typed, as they can return so many things like multiple data tables, exceptions, etc.

**Comment by JordanMarr** [comment]
> SQLProvider Stored procedures return values are not strongly typed, as they can return so many things like multiple data tables, exceptions, etc.

Hmm, I guess that means they won't be as hard as view then...

**Comment by JordanMarr** [comment]
> Thanks! Merged and released to NuGet 1.1.96.

Thanks for the fast turnaround! The blog announcement is posted. 🎉

I am giving up on trying to get the bullet point under the ResolutionPath instructions to render. 
For some reason the asterisks didn’t work. 
¯\_(ツ)_/¯

**Pull request merged**
