### PR TITLE
Initial version of GroupBy working.

### PR DESCRIPTION
**Pull request by Thorium**
Simple version of group-by done. 
No join and multi-column-key-support yet.

This kind of simple group-by works:

```fsharp
[<Test>]
let ``verify groupBy results``() = 
    let dc = sql.GetDataContext()
    let enumtest =
        query {
            for cust in dc.Main.Customers do
            select (cust)
        } |> Seq.toList
    let inlogics = 
        query {
            for cust in enumtest do
            groupBy cust.City into c
            select (c.Key, c.Count())
        } |> Seq.toArray |> Array.sortBy (fun (k,v) -> k )

    let groupqry = 
        query {
            for cust in dc.Main.Customers do
            groupBy cust.City into c
            select (c.Key, c.Count())
        } |> Seq.toArray |> Array.sortBy (fun (k,v) -> k )

    CollectionAssert.AreEqual(inlogics,groupqry)
```

### CODE REVIEW

**Comment by Thorium** [comment]
Implementation details:

- SqlGroupingQueryable<key, SqlEntity> is a structure to make it easier to return IGrouping, the old SqlQuerable was returning enumerables of SqlEntities, not groups.
- SelectMany data has now option of GroupData. SelectMany was used because I expected in the future of group-join-select-complexity to grow, so it is located now more near the already than a separate sqlQuery structure.
- Selection in SQL-clauses will come like SELECT City.Count as "City.[Count]"
- GroupResultItems is an item to create key-igrouping-structure. 
- From the select projection, Enumerable.Count() is replaced to GroupResultItems.AggregateCount call and this way it will fetch the SQL result instead of actually counting anything.
- SqlEntities are still used for aggregation of data as was previously, selection columns will be in data (and ColumnValues).
- IAsyncEnumerable is just to simplify SqlQueryable async code.

**Comment by Thorium** [comment]
Interesting future extension points:

- Joins projections with groupby: SqlRuntime.QueryableExtension.fs about line 260, `Expression.Parameter(typeof<SqlEntity>,"result")`, and projection in SqlRuntime.Linq about line 635: `if v1.Name.StartsWith "_arg"` 

- GroupVal and other more complex overrides of GroupBy: SqlRuntime.Linq about line 430: `| MethodCall(None, (MethodWithName "GroupBy" | MethodWithName "GroupJoin" as meth)`, and GroupBy with SelectMany: SqlRuntime.Linq about line 536: `| MethodCall(None, (MethodWithName "GroupBy" | MethodWithName "GroupJoin" as meth),`

- Groups with multiple columns: SQL-clauses are already generated. SqlRuntime.Linq about line 53, and how to create correct aggregate of GroupResultItems distinctItem.ColumnValues when we have multiple keys.

- Reduce and map the aggregation operations by columns: SqlRuntime.QueryableExtension.fs about line 317 should collect the aggregation values by selected columns, not for all key columns if many.

**Comment by Thorium** [comment]
Ping #357 #317

**Comment by Thorium** [comment]
Should I merge this initial version?
Do someone want to make a small code review: could some things be done an easier way?

**Comment by pezipink** [comment]
I'll try and have a study of this on the weekend!

**Comment by colinbull** [comment]
Awesome... Sauce.. 

winnie-the-pooh

**Comment by Thorium** [comment]
Any news on this?

My comments:
- You can criticize the source code, I don't take it personally. That is part of my Finnish background.
- It's not totally complete all-scenarios-group-by, it adds just simple one-column group-by.
- It was easiest solution I found to do things. If you find easier, make a PR. I will accept changes to this PR also.
- On the other hand, it's adding a new feature that we don't currently have and it's not breaking any existing features.
- There are unit tests to show what it adds.

**Comment by colinbull** [comment]
I have just had a play with this and I couldn't break it. IMHO I reckon this is good to merge as long as the limitation on one column is clear in the docs.

**Comment by Thorium** [comment]
I did continue a bit.
Now this kind of aggregates and having-clauses are working:
```fsharp
query {
    for od in dc.Main.OrderDetails do
    groupBy od.ProductId into p
    where (p.Key > 3L)
    where (p.Count() > 2)
    select (p.Key, p.Sum(fun f -> f.UnitPrice), p.Sum(fun f -> f.Discount))
} |> Seq.toList
```
...producing query like this:

```sql
SELECT 
   [OrderDetails].[ProductID], 
   SUM([OrderDetails].[Discount]) as '[Discount].[SUM]', 
   SUM([OrderDetails].[UnitPrice]) as '[UnitPrice].[SUM]' 
FROM main.OrderDetails as [OrderDetails]  
GROUP BY [OrderDetails].[ProductID] 
HAVING (
   ([OrderDetails].[ProductID]> @param1) AND 
   (COUNT( 1 ) > @param2)
) 
- params @param1 - 3L; @param2 - 2; 
```

**Comment by pezipink** [comment]
Sorry @Thorium I did not manage to look at this properly, you know what this time of year is like!  I'm sure it is great though, still intend to have a look in the near future ....

**Pull request merged**
