### PR TITLE
Postgres & MySQL add quotation mark to column names in generated SQL statement

### PR DESCRIPTION
**Pull request by ingted**
[ISSUE 294](https://github.com/fsprojects/SQLProvider/issues/294)

### CODE REVIEW

**Comment by ingted** [comment]
I could build these changes in my computer... just don't understand why it fails here...

**Comment by ingted** [comment]
It said "The command "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF" failed and exited with 2 during ."

This should be the build server issues, not code issues...

**Comment by Thorium** [comment]
Thanks...
For MySql there are both Replace "[" with quote, and the new addition of quote. So is there a danger of creating multiple quotes?

**Comment by ingted** [comment]
Hi Thorium,

The code changes are what I use in our production environment ETL application.
I think there should not any  "[" or "]" in any MySQL code... so the replace just do nothing...

Sorry that I have to say I didn't think very deep about it (I just ignore...)
So IMO, my changes are not a good change for long term...

Would you mind give me some suggestions?
I will do another change and try making it more precise...

Thank you!!

**Comment by Thorium** [comment]
My bad, the other one was table name and the other one was column names.
This is ok, thanks!

**Pull request merged**
