### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by tforkmann**
Babysteps in Documentation:

- Adding Docs for MSSQL.fsx
- Adding mappers.fsx

### CODE REVIEW

**Comment by pezipink** [comment]
Hi, thanks for this - I assume you are not aware of our `MapTo<T>` function?  It does that mapping to record types automatically for you, though it is a little slower

`MapTo<Employee>()`

Have you seen it?

**Comment by tforkmann** [comment]
Ohh, sweet!
Gonna test it today.

**Comment by tforkmann** [comment]
Works like a charm! Going to fix the docu

**Comment by tforkmann** [comment]
Guess I got a little bit too excited there.
Its compiling but not working in my project. 

Suave returns a System.Reflection.TargetParameterCountException at the end.

We had that issue before that's why we created our own mapper.
https://github.com/fsprojects/SQLProvider/issues/179

We are only looking for the name of the type.
I tried property matching with 'MapTo' but I didn't really got that working. 
https://github.com/fsprojects/SQLProvider/blob/master/tests/SqlProvider.Tests/scripts/PostgreSQLTests.fsx#L144-L151

Guess I have to stick to the old mapper...

**Pull request merged**
